### ISSUE TITLE
Duplicate module name: react-native

### ISSUE THREAD

**Issue by zukilover** [MiLeung/done-bar#11]
This warning is caused by a @providesModule declaration with the same name across two different files.
jest-haste-map: @providesModule naming collision:
  Duplicate module name: react-native
  Paths: /Library/WebServer/Documents/cimbrtbmobile/node_modules/react-native/package.json collides with /Library/WebServer/Documents/cimbrtbmobile/node_modules/done-bar/node_modules/react-native/package.json

**Comment by mileung** [comment]
Now try it. I basically just removed a lot of junk files including the react and react-native dependencies in the package.json. Kinda bad, but you wouldn't install this package anyways if you weren't making something with RN which requires you to install react and react-native.
