### ISSUE TITLE
Keyboard.dismiss is not defined on RN 0.33

### ISSUE THREAD

**Issue by garlab** [MiLeung/done-bar#2]
Hi,

I tried to use done-bar on a project stuck with react-native@0.33 but I got the error `_reactNative.Keyboard.dismiss is not a function`, because `Keyboard.dismiss` is not defined on old versions of RN.

This can be easily solved app-side by this polyfill

    import { Keyboard } from 'react-native';
    import TextInputState from 'TextInputState';
    
    if (!Keyboard.dismiss) {
      Keyboard.dismiss = () => TextInputState.blurTextInput(TextInputState.currentlyFocusedField());
    }

Just to let you know in case you want to support previous versions.

**Comment by mileung** [comment]
Thanks!  Added this in 1.0.1 which just got published

**Comment by garlab** [comment]
I tried to update to 1.0.1 and now I got that error:

    Unable to resolve module TextInputState from /Users/<project_dir>/node_modules/done-bar/src/DoneBar.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/TextInputState and its parent directories

I think `import TextInputState from 'TextInputState'` will only be resolved when the project uses the same version of RN as the lib. However this should work all the time:

    import TextInputState from 'react-native/lib/TextInputState';

**Comment by mileung** [comment]
Added this is 1.0.2 =D
